version: '3.7'

services:
  db-postgres-challenge-banking-system:
    restart: always
    image: postgres:15
    container_name: db-challenge-banking-system
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - ./.docker/database/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - '5433:5432'
    networks:
      - my-networks

networks:
  my-networks:
    driver: bridge
